# Generated by Django 5.1.3 on 2026-09-10 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_flavorstock_colorstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('discount_type', models.CharField(choices=[('percent', 'Процент'), ('fixed', 'Фиксированная сумма')], default='percent', max_length=10, verbose_name='Тип скидки')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Размер скидки')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Мин. сумма заказа')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Действует с')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Действует до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Лимит использований')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Использовано раз')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.AlterModelOptions(
            name='colorstock',
            options={'verbose_name': 'Остаток цвета', 'verbose_name_plural': 'Остатки цветов'},
        ),
        migrations.AlterModelOptions(
            name='flavorstock',
            options={'verbose_name': 'Остаток вкуса', 'verbose_name_plural': 'Остатки вкусов'},
        ),
        migrations.AlterField(
            model_name='colorstock',
            name='color',
            field=models.CharField(max_length=100, verbose_name='Название цвета'),
        ),
        migrations.AlterField(
            model_name='colorstock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_stocks', to='catalog.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='colorstock',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество на складе'),
        ),
        migrations.AlterField(
            model_name='flavorstock',
            name='flavor',
            field=models.CharField(max_length=100, verbose_name='Название вкуса'),
        ),
        migrations.AlterField(
            model_name='flavorstock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavor_stocks', to='catalog.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='flavorstock',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество на складе'),
        ),
        migrations.AlterUniqueTogether(
            name='colorstock',
            unique_together={('product', 'color')},
        ),
        migrations.AlterUniqueTogether(
            name='flavorstock',
            unique_together={('product', 'flavor')},
        ),
    ]
