# Generated by Django 6.1 on 2026-09-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.CharField(max_length=100, unique=True, verbose_name='Telegram-ник')),
                ('reason', models.TextField(blank=True, verbose_name='Причина блокировки')),
                ('blocked_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата блокировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Заблокированный пользователь',
                'verbose_name_plural': 'Заблокированные пользователи',
                'ordering': ['-blocked_at'],
            },
        ),
    ]
