# Generated by Django 6.1 on 2026-08-30 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название вкуса')),
                ('price_extra', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Доплата')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Вкус',
                'verbose_name_plural': 'Вкусы',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='flavor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.flavor', verbose_name='Выбранный вкус'),
        ),
        migrations.AddField(
            model_name='product',
            name='flavors',
            field=models.ManyToManyField(blank=True, to='catalog.flavor', verbose_name='Доступные вкусы'),
        ),
    ]
