# Generated by Django 6.1 on 2026-08-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.AddField(
            model_name='order',
            name='telegram',
            field=models.CharField(default='', help_text='Введите ваш Telegram-ник без @', max_length=100, verbose_name='Telegram'),
            preserve_default=False,
        ),
    ]
