# Generated by Django 6.1 on 2026-08-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_order_name_remove_order_phone_order_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='telegram',
            field=models.CharField(max_length=100, verbose_name='Telegram'),
        ),
    ]
