# Generated by Django 6.1 on 2026-08-31 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='flavor',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Выбранный вкус'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='product',
            name='flavors',
        ),
        migrations.DeleteModel(
            name='Flavor',
        ),
        migrations.AddField(
            model_name='product',
            name='flavors',
            field=models.TextField(blank=True, help_text='Введите вкусы через запятую (например: Клубника, Шоколад, Ваниль)', verbose_name='Вкусы'),
        ),
    ]
