# Generated by Django 6.1 on 2026-08-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_order_flavor_remove_product_flavors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='flavor',
        ),
        migrations.RemoveField(
            model_name='product',
            name='flavors',
        ),
        migrations.AddField(
            model_name='order',
            name='flavors',
            field=models.TextField(blank=True, help_text='Вкусы через запятую', verbose_name='Выбранные вкусы'),
        ),
        migrations.AddField(
            model_name='product',
            name='flavor_1',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Вкус 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='flavor_10',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Вкус 10'),
        ),
        migrations.AddField(
            model_name='product',
            name='flavor_2',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Вкус 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='flavor_3',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Вкус 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='flavor_4',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Вкус 4'),
        ),
        migrations.AddField(
            model_name='product',
            name='flavor_5',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Вкус 5'),
        ),
        migrations.AddField(
            model_name='product',
            name='flavor_6',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Вкус 6'),
        ),
        migrations.AddField(
            model_name='product',
            name='flavor_7',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Вкус 7'),
        ),
        migrations.AddField(
            model_name='product',
            name='flavor_8',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Вкус 8'),
        ),
        migrations.AddField(
            model_name='product',
            name='flavor_9',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Вкус 9'),
        ),
    ]
