# Generated by Django 6.1 on 2026-08-31 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_order_flavor_remove_product_flavors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='flavor_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='flavor_10',
        ),
        migrations.RemoveField(
            model_name='product',
            name='flavor_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='flavor_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='flavor_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='flavor_5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='flavor_6',
        ),
        migrations.RemoveField(
            model_name='product',
            name='flavor_7',
        ),
        migrations.RemoveField(
            model_name='product',
            name='flavor_8',
        ),
        migrations.RemoveField(
            model_name='product',
            name='flavor_9',
        ),
        migrations.AddField(
            model_name='product',
            name='flavors',
            field=models.TextField(blank=True, default='', help_text='Введите каждый вкус с новой строки', verbose_name='Вкусы'),
        ),
    ]
