# Generated by Django 6.1 on 2026-08-31 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_product_flavor_1_remove_product_flavor_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.TextField(blank=True, default='', help_text='Введите каждый цвет с новой строки', verbose_name='Цвета'),
        ),
    ]
