# Generated by Django 6.1 on 2026-08-31 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_product_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='flavors',
        ),
        migrations.AddField(
            model_name='order',
            name='color',
            field=models.CharField(blank=True, max_length=100, verbose_name='Выбранный цвет'),
        ),
        migrations.AddField(
            model_name='order',
            name='flavor',
            field=models.CharField(blank=True, max_length=100, verbose_name='Выбранный вкус'),
        ),
    ]
