# Generated by Django 6.1 on 2026-09-02 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_order_quantity_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='flavors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.TextField(blank=True, default='', verbose_name='Цвета'),
        ),
        migrations.CreateModel(
            name='FlavorStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor', models.CharField(max_length=100, verbose_name='Название вкуса')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flavor_stocks', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Остаток вкуса',
                'verbose_name_plural': 'Остатки вкусов',
                'unique_together': {('product', 'flavor')},
            },
        ),
    ]
