# Generated by Django 6.1 on 2026-09-02 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_remove_product_flavors_remove_product_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='colors',
        ),
        migrations.CreateModel(
            name='ColorStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100, verbose_name='Название цвета')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Количество на складе')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_stocks', to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Остаток цвета',
                'verbose_name_plural': 'Остатки цветов',
                'unique_together': {('product', 'color')},
            },
        ),
    ]
